### PR TITLE
DNM: addons section

### PR DESCRIPTION
**Pull request by tomwayson**
This is 1st half of the addon part. 2nd half coming soon.

Basically we add ember-bootstrap to get this working:

toggle-mobile-navbar

### CODE REVIEW

**Comment by tomwayson** [comment]
@dbouwman I think to add your drop down to the nav menu all you will have to do now is something like:

```hbs
      {{#nav.dropdown as |dd|}}
        {{#dd.toggle}}Dropdown <span class="caret"></span>{{/dd.toggle}}
        {{#dd.menu as |ddm|}}
          {{#ddm.item}}
            <a href="#" {{action 'signout'}}>Sign Out</a>
          {{/ddm.item}}
        {{/dd.menu}}
      {{/nav.dropdown}}
```

**Comment by tomwayson** [comment]
OK, the addons section is done, _but_ the paging component looks like this:

image

this is b/c [BS4's pagination needs add'l classes](https://getbootstrap.com/docs/4.0/components/pagination/) that we don't have in eapc b/c it's based on [BS3's pagination](https://getbootstrap.com/docs/3.3/components/#pagination). Options:

1. roll this back to BS3 (safest)
2. add the classes to eapc and hope they don't break anything

for the latter, as Alex and I recently discovered, we're barely even using this component in the Hub apps, outside of the item picker, it's only being used in one spot (the other pagers are using one of the other 4 paging components). Also, I think we can make a release in eapc w/o necessarily bumping in Hub until we've had a chance to flesh it out.

On the other hand, there are likely going to be other things that break in BS4 as we go forward, so the safest thing to do is go back to BS3. Of all the new shiny things, BS4 is the one I'm least concerned w/ having in the app. I want Ember 3 and JSAPI 4 for sure.

Thoughts?

**Comment by mjuniper** [comment]
What if we add a `bs4=true` attribute to the component that it can use to decide what classes to apply?

**Comment by tomwayson** [comment]
closing in favor of #10

**Pull request closed without merging**
